# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(609, 497)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sheet = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sheet.sizePolicy().hasHeightForWidth())
        self.sheet.setSizePolicy(sizePolicy)
        self.sheet.setMinimumSize(QtCore.QSize(0, 0))
        self.sheet.setObjectName("sheet")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.sheet)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(863, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.sheet)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_animation = QtWidgets.QLabel(Dialog)
        self.label_animation.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_animation.setText("")
        self.label_animation.setTextFormat(QtCore.Qt.AutoText)
        self.label_animation.setWordWrap(True)
        self.label_animation.setObjectName("label_animation")
        self.verticalLayout.addWidget(self.label_animation)
        self.button_steps = QtWidgets.QPushButton(Dialog)
        self.button_steps.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_steps.sizePolicy().hasHeightForWidth())
        self.button_steps.setSizePolicy(sizePolicy)
        self.button_steps.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.button_steps.setObjectName("button_steps")
        self.verticalLayout.addWidget(self.button_steps)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.button_colors = QtWidgets.QPushButton(Dialog)
        self.button_colors.setObjectName("button_colors")
        self.verticalLayout.addWidget(self.button_colors)
        self.button_z = QtWidgets.QPushButton(Dialog)
        self.button_z.setObjectName("button_z")
        self.verticalLayout.addWidget(self.button_z)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_steps.setText(_translate("Dialog", "пошагово"))
        self.button_colors.setText(_translate("Dialog", "цвета"))
        self.button_z.setText(_translate("Dialog", "z буффер"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
